# Generated by Django 3.2.5 on 2023-02-13 02:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230213_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
