# Generated by Django 3.2.5 on 2023-02-13 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
